name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Install system dependencies
            sudo apt update && sudo apt install -y git curl unzip

            # Install Node.js 18 if not already installed
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt install -y nodejs
            fi

            # Install Ollama if missing
            if ! command -v ollama &> /dev/null; then
              curl -fsSL https://ollama.com/install.sh | sh
            fi

            # Configure Ollama to listen on all IPs
            mkdir -p ~/.ollama
            echo 'host = "0.0.0.0"' > ~/.ollama/config

            # Restart Ollama service
            pkill ollama || true
            nohup ollama serve > ollama.log 2>&1 &

            # Clone or update the project repository
            if [ ! -d m-nextjs-ollama-llm-ui ]; then
              git clone https://github.com/MaisaSh99/m-nextjs-ollama-llm-ui.git
            else
              cd m-nextjs-ollama-llm-ui && git pull && cd ..
            fi

            cd m-nextjs-ollama-llm-ui

            # Create pets.json file if it doesn't exist
            mkdir -p data
            if [ ! -f data/pets.json ]; then
              echo '[]' > data/pets.json
            fi
            chmod 664 data/pets.json

            # Create or overwrite .env file with S3 + region
            echo "OLLAMA_URL=http://${{ secrets.EC2_HOST }}:11434" > .env
            echo "NODE_ENV=production" >> .env
            echo "PETS_JSON_PATH=./data/pets.json" >> .env
            echo "S3_BUCKET=m-adoption-images" >> .env
            echo "AWS_REGION=us-east-2" >> .env

            # Install dependencies and build
            npm ci
            npm run build

            # Ensure systemd service uses `npm run start`
            sed -i 's/npm run dev/npm run start/' nextjs-ollama-llm-ui.service || true

            # Install or reload the systemd service
            sudo cp nextjs-ollama-llm-ui.service /etc/systemd/system/nextjs-ollama-llm-ui.service
            sudo systemctl daemon-reload
            sudo systemctl enable nextjs-ollama-llm-ui.service
            sudo systemctl restart nextjs-ollama-llm-ui.service
          EOF
