name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Update and install dependencies
            sudo apt update && sudo apt install -y git curl unzip

            # Install Node.js 18 if not present
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt install -y nodejs
            fi

            # Install Ollama if not installed
            if ! command -v ollama &> /dev/null; then
              curl -fsSL https://ollama.com/install.sh | sh
            fi

            # Configure Ollama to listen on all IPs
            mkdir -p ~/.ollama
            echo 'host = "0.0.0.0"' > ~/.ollama/config

            # Start Ollama server
            pkill ollama || true
            nohup ollama serve > ollama.log 2>&1 &

            # Clone or update the app repo
            if [ ! -d m-nextjs-ollama-llm-ui ]; then
              git clone https://github.com/MaisaSh99/m-nextjs-ollama-llm-ui.git
            else
              cd m-nextjs-ollama-llm-ui && git pull && cd ..
            fi

            cd m-nextjs-ollama-llm-ui

            # Ensure pets.json exists and is writable
            mkdir -p data
            touch data/pets.json
            echo '[]' > data/pets.json
            chmod 664 data/pets.json

            # Set environment variables
            echo 'OLLAMA_URL=http://${{ secrets.EC2_HOST }}:11434' > .env
            echo 'NODE_ENV=production' >> .env
            echo 'PETS_JSON_PATH=./data/pets.json' >> .env

            # Install dependencies and build app
            npm ci
            npm run build

            # Restart systemd service if defined
            sudo systemctl daemon-reload
            sudo systemctl enable nextjs-ollama-llm-ui.service
            sudo systemctl restart nextjs-ollama-llm-ui.service
          EOF
